apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-basic
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    - repoURL: https://github.com/argoproj/argocd-example-apps.git
      targetRevision: HEAD
      path: guestbook
    - repoURL: 'https://github.com/dein-repo/dein-projekt.git' # Ersetze durch deine Repo-URL
      targetRevision: HEAD # Oder einen spezifischen Branch/Tag
      path: cnpg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true